### ISSUE TITLE
Build not working with plantuml diagrams

### ISSUE THREAD

**Issue by ronaldtse** [CalConnect/csd-lightweight-doc#1]
https://travis-ci.com/CalConnect/csd-lightweight-doc/builds/114523679?utm_medium=notification&utm_source=email

@CAMOBAP795 can you help fix this? Thanks!

**Comment by CAMOBAP795** [comment]
Here is a problem

```
Package graphviz is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'graphviz' has no installation candidate
```

Looking for solution

**Comment by CAMOBAP795** [comment]
@ronaldtse ready for review https://github.com/CalConnect/csd-lightweight-doc/pull/2
